name: Assignment Overview
description: Starting point for new Data Lab projects
title: "[COUNTRY] | [PROJECT]"
labels: data lab assignment
body:
- type: markdown
  attributes:
    value: |
      ### Project Overview and Core Information
- type: input
  id: contact
  attributes:
    label: Client Contact Email(s)
    placeholder: ex. email@example.com
  validations:
    required: false
- type: input
  id: charge-code
  attributes:
    label: Project Charge Code
    placeholder: ex. AA-P123456-GPLG-TF01234 or IO 123456
  validations:
    required: false
- type: input
  id: manager
  attributes:
    label: Project Manager
    placeholder: Person responsible for client relationship and final deliverables
  validations:
    required: false
- type: input
  id: share-point
  attributes:
    label: Project Sharepoint URL
- type: input
  id: web-book
  attributes:
    label: Project Web Book URL
- type: input
  id: proposal
  attributes:
    label: Link to Proposal and Work Plan Shared with Client
- type: textarea
  id: assignment-summary
  attributes:
    label: Project Assignment
    description: Please provide a summary of the project and assignment.
    
